#!/usr/bin/env bash
###############################################################################
# 01-create-network.sh
#
# Does exactly what terraform/01-network.tf does, but with the AWS CLI.
# Use this to understand what Terraform is doing under the hood, or as a
# fallback if Terraform is unavailable.
#
# Every ID it creates is appended to ./keycloak-state.env so the later
# scripts (and the destroy scripts) can find them again.
#
# Usage:  ./01-create-network.sh
###############################################################################

set -euo pipefail

# ---------------------------------------------------------------------------
# CONFIGURATION - edit these to match your situation
# ---------------------------------------------------------------------------
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
PROJECT="${PROJECT:-keycloak-demo}"
MY_IP_CIDR="${MY_IP_CIDR:-68.32.112.68/32}"
VPC_CIDR="${VPC_CIDR:-10.42.0.0/16}"

STATE_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/keycloak-state.env"

# ---------------------------------------------------------------------------
# Small helpers so the output is readable
# ---------------------------------------------------------------------------
step() { echo ""; echo "=========================================================="; echo ">>> $*"; echo "=========================================================="; }
info() { echo "    $*"; }
save() { echo "export $1='$2'" >> "$STATE_FILE"; info "saved $1=$2"; }

# ---------------------------------------------------------------------------
# Preflight checks - fail early with a clear message
# ---------------------------------------------------------------------------
step "Preflight checks"

command -v aws >/dev/null || { echo "ERROR: aws CLI not installed. See https://aws.amazon.com/cli/"; exit 1; }
command -v jq  >/dev/null || { echo "ERROR: jq not installed. Try: sudo dnf install jq  (or brew install jq)"; exit 1; }

AWS_CLI_VERSION=$(aws --version 2>&1 | awk '{print $1}')
info "AWS CLI: $AWS_CLI_VERSION"

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text) || {
  echo "ERROR: cannot reach AWS. Run 'aws configure' first."; exit 1; }
info "Account: $ACCOUNT_ID   Region: $AWS_DEFAULT_REGION"

# A random 6-character suffix so names never collide with an old run
SUFFIX=$(openssl rand -hex 3)

# Start a fresh state file
cat > "$STATE_FILE" <<EOF
# Generated by 01-create-network.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source this file before running the other scripts:  source ./keycloak-state.env
export AWS_DEFAULT_REGION='$AWS_DEFAULT_REGION'
export PROJECT='$PROJECT'
export MY_IP_CIDR='$MY_IP_CIDR'
export ACCOUNT_ID='$ACCOUNT_ID'
export SUFFIX='$SUFFIX'
EOF
info "State file: $STATE_FILE"

# ---------------------------------------------------------------------------
# 1. VPC
# ---------------------------------------------------------------------------
step "1/9  Creating the VPC ($VPC_CIDR)"
# A VPC is your own private network inside AWS. Think of it as renting an
# empty office building: you decide the room layout and who gets a key.

VPC_ID=$(aws ec2 create-vpc \
  --cidr-block "$VPC_CIDR" \
  --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=${PROJECT}-vpc},{Key=Project,Value=${PROJECT}},{Key=ManagedBy,Value=awscli}]" \
  --query 'Vpc.VpcId' --output text)
save VPC_ID "$VPC_ID"

# These two settings let resources inside the VPC resolve DNS names.
# RDS gives you a hostname, not an IP, so without these Keycloak cannot
# find the database at all.
aws ec2 modify-vpc-attribute --vpc-id "$VPC_ID" --enable-dns-support '{"Value":true}'
aws ec2 modify-vpc-attribute --vpc-id "$VPC_ID" --enable-dns-hostnames '{"Value":true}'
info "DNS support and hostnames enabled"

# ---------------------------------------------------------------------------
# 2. Internet Gateway
# ---------------------------------------------------------------------------
step "2/9  Creating and attaching the Internet Gateway"
# The IGW is the front door of the building. Without it nothing inside the
# VPC can talk to the internet, and you cannot talk to it.

IGW_ID=$(aws ec2 create-internet-gateway \
  --tag-specifications "ResourceType=internet-gateway,Tags=[{Key=Name,Value=${PROJECT}-igw},{Key=Project,Value=${PROJECT}}]" \
  --query 'InternetGateway.InternetGatewayId' --output text)
save IGW_ID "$IGW_ID"

aws ec2 attach-internet-gateway --internet-gateway-id "$IGW_ID" --vpc-id "$VPC_ID"
info "Attached $IGW_ID to $VPC_ID"

# ---------------------------------------------------------------------------
# 3. Subnets
# ---------------------------------------------------------------------------
step "3/9  Creating subnets"
# Subnets are rooms inside the building.
#  - PUBLIC room  : has a door to the street. Keycloak lives here.
#  - PRIVATE rooms: no door to the street. The database lives here.
# RDS insists on at least two private rooms in two different buildings
# (Availability Zones) so it can fail over if one loses power.

AZ1=$(aws ec2 describe-availability-zones --query 'AvailabilityZones[0].ZoneName' --output text)
AZ2=$(aws ec2 describe-availability-zones --query 'AvailabilityZones[1].ZoneName' --output text)
info "Using AZs: $AZ1 and $AZ2"
save AZ1 "$AZ1"
save AZ2 "$AZ2"

PUBLIC_SUBNET_ID=$(aws ec2 create-subnet \
  --vpc-id "$VPC_ID" --cidr-block "10.42.1.0/24" --availability-zone "$AZ1" \
  --tag-specifications "ResourceType=subnet,Tags=[{Key=Name,Value=${PROJECT}-public-a},{Key=Project,Value=${PROJECT}}]" \
  --query 'Subnet.SubnetId' --output text)
save PUBLIC_SUBNET_ID "$PUBLIC_SUBNET_ID"

# Anything launched here automatically gets a public IP address.
aws ec2 modify-subnet-attribute --subnet-id "$PUBLIC_SUBNET_ID" --map-public-ip-on-launch
info "Public subnet will auto-assign public IPs"

PRIVATE_SUBNET_A=$(aws ec2 create-subnet \
  --vpc-id "$VPC_ID" --cidr-block "10.42.11.0/24" --availability-zone "$AZ1" \
  --tag-specifications "ResourceType=subnet,Tags=[{Key=Name,Value=${PROJECT}-private-a},{Key=Project,Value=${PROJECT}}]" \
  --query 'Subnet.SubnetId' --output text)
save PRIVATE_SUBNET_A "$PRIVATE_SUBNET_A"

PRIVATE_SUBNET_B=$(aws ec2 create-subnet \
  --vpc-id "$VPC_ID" --cidr-block "10.42.12.0/24" --availability-zone "$AZ2" \
  --tag-specifications "ResourceType=subnet,Tags=[{Key=Name,Value=${PROJECT}-private-b},{Key=Project,Value=${PROJECT}}]" \
  --query 'Subnet.SubnetId' --output text)
save PRIVATE_SUBNET_B "$PRIVATE_SUBNET_B"

# ---------------------------------------------------------------------------
# 4. Route tables
# ---------------------------------------------------------------------------
step "4/9  Creating route tables"
# A route table is the set of road signs. "0.0.0.0/0" means "anywhere else",
# so pointing it at the IGW means "for anything not in this VPC, use the
# front door."

PUBLIC_RT_ID=$(aws ec2 create-route-table --vpc-id "$VPC_ID" \
  --tag-specifications "ResourceType=route-table,Tags=[{Key=Name,Value=${PROJECT}-rt-public},{Key=Project,Value=${PROJECT}}]" \
  --query 'RouteTable.RouteTableId' --output text)
save PUBLIC_RT_ID "$PUBLIC_RT_ID"

aws ec2 create-route --route-table-id "$PUBLIC_RT_ID" \
  --destination-cidr-block "0.0.0.0/0" --gateway-id "$IGW_ID" >/dev/null
aws ec2 associate-route-table --route-table-id "$PUBLIC_RT_ID" --subnet-id "$PUBLIC_SUBNET_ID" >/dev/null
info "Public subnet routes to the internet"

PRIVATE_RT_ID=$(aws ec2 create-route-table --vpc-id "$VPC_ID" \
  --tag-specifications "ResourceType=route-table,Tags=[{Key=Name,Value=${PROJECT}-rt-private},{Key=Project,Value=${PROJECT}}]" \
  --query 'RouteTable.RouteTableId' --output text)
save PRIVATE_RT_ID "$PRIVATE_RT_ID"

# Deliberately NO 0.0.0.0/0 route here. The database is sealed off.
# A NAT Gateway would give it outbound access for about $32/month. We skip it.
aws ec2 associate-route-table --route-table-id "$PRIVATE_RT_ID" --subnet-id "$PRIVATE_SUBNET_A" >/dev/null
aws ec2 associate-route-table --route-table-id "$PRIVATE_RT_ID" --subnet-id "$PRIVATE_SUBNET_B" >/dev/null
info "Private subnets have NO route to the internet (intentional)"

# ---------------------------------------------------------------------------
# 5. Security group for Keycloak
# ---------------------------------------------------------------------------
step "5/9  Creating the Keycloak security group"
# A security group is a firewall wrapped around one resource. It is
# "stateful": if you allow a request in, the reply is automatically allowed
# back out. You only ever write the inbound rules you actually want.

KEYCLOAK_SG_ID=$(aws ec2 create-security-group \
  --group-name "${PROJECT}-keycloak-sg-${SUFFIX}" \
  --description "Keycloak admin console and SSH from one IP only" \
  --vpc-id "$VPC_ID" \
  --tag-specifications "ResourceType=security-group,Tags=[{Key=Name,Value=${PROJECT}-keycloak-sg},{Key=Project,Value=${PROJECT}}]" \
  --query 'GroupId' --output text)
save KEYCLOAK_SG_ID "$KEYCLOAK_SG_ID"

info "Allowing 8443 (HTTPS) from $MY_IP_CIDR"
aws ec2 authorize-security-group-ingress --group-id "$KEYCLOAK_SG_ID" \
  --ip-permissions "IpProtocol=tcp,FromPort=8443,ToPort=8443,IpRanges=[{CidrIp=${MY_IP_CIDR},Description='Keycloak HTTPS from my IP'}]" >/dev/null

info "Allowing 8080 (HTTP) from $MY_IP_CIDR  - for troubleshooting"
aws ec2 authorize-security-group-ingress --group-id "$KEYCLOAK_SG_ID" \
  --ip-permissions "IpProtocol=tcp,FromPort=8080,ToPort=8080,IpRanges=[{CidrIp=${MY_IP_CIDR},Description='Keycloak HTTP from my IP'}]" >/dev/null

info "Allowing 22 (SSH) from $MY_IP_CIDR"
aws ec2 authorize-security-group-ingress --group-id "$KEYCLOAK_SG_ID" \
  --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${MY_IP_CIDR},Description='SSH from my IP'}]" >/dev/null

# Note: AWS adds an "allow all outbound" rule automatically. Keycloak needs
# it to download itself and to reach Secrets Manager, so we leave it alone.

# ---------------------------------------------------------------------------
# 6. Security group for the database
# ---------------------------------------------------------------------------
step "6/9  Creating the database security group"
# The clever bit: the source of this rule is the KEYCLOAK SECURITY GROUP,
# not an IP address. Any instance wearing that group can reach the database.
# Replace the instance, change its IP, add a second one - the rule still works.

DB_SG_ID=$(aws ec2 create-security-group \
  --group-name "${PROJECT}-db-sg-${SUFFIX}" \
  --description "PostgreSQL 5432 from the Keycloak security group only" \
  --vpc-id "$VPC_ID" \
  --tag-specifications "ResourceType=security-group,Tags=[{Key=Name,Value=${PROJECT}-db-sg},{Key=Project,Value=${PROJECT}}]" \
  --query 'GroupId' --output text)
save DB_SG_ID "$DB_SG_ID"

aws ec2 authorize-security-group-ingress --group-id "$DB_SG_ID" \
  --ip-permissions "IpProtocol=tcp,FromPort=5432,ToPort=5432,UserIdGroupPairs=[{GroupId=${KEYCLOAK_SG_ID},Description='Postgres from Keycloak only'}]" >/dev/null
info "Port 5432 open ONLY to members of $KEYCLOAK_SG_ID"

# Remove the default allow-all-outbound rule. A database has no business
# starting connections to the internet.
aws ec2 revoke-security-group-egress --group-id "$DB_SG_ID" \
  --ip-permissions "IpProtocol=-1,IpRanges=[{CidrIp=0.0.0.0/0}]" >/dev/null 2>&1 || true
info "Removed default allow-all egress from the database"

# ---------------------------------------------------------------------------
# 7. RDS subnet group
# ---------------------------------------------------------------------------
step "7/9  Creating the RDS DB subnet group"
# RDS will not launch until you tell it which subnets it is permitted to use.

DB_SUBNET_GROUP="${PROJECT}-db-subnets-${SUFFIX}"
aws rds create-db-subnet-group \
  --db-subnet-group-name "$DB_SUBNET_GROUP" \
  --db-subnet-group-description "Private subnets for the Keycloak database" \
  --subnet-ids "$PRIVATE_SUBNET_A" "$PRIVATE_SUBNET_B" \
  --tags "Key=Project,Value=${PROJECT}" >/dev/null
save DB_SUBNET_GROUP "$DB_SUBNET_GROUP"

# ---------------------------------------------------------------------------
# 8. IAM role - least privilege
# ---------------------------------------------------------------------------
step "8/9  Creating the IAM role for the Keycloak instance"
# An IAM role is a badge the server wears. It grants exactly two abilities:
#   * read the one secret holding the database password
#   * talk to SSM so you can open a shell without SSH
# Nothing more. No "*" on actions, and the resource is pinned to one ARN
# pattern rather than every secret in the account.

ROLE_NAME="${PROJECT}-keycloak-role-${SUFFIX}"
save ROLE_NAME "$ROLE_NAME"

# The trust policy answers: WHO is allowed to wear this badge?
TRUST_POLICY=$(cat <<'JSON'
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowEC2ToAssume",
      "Effect": "Allow",
      "Principal": { "Service": "ec2.amazonaws.com" },
      "Action": "sts:AssumeRole"
    }
  ]
}
JSON
)

aws iam create-role \
  --role-name "$ROLE_NAME" \
  --description "Least privilege role for the Keycloak EC2 instance" \
  --assume-role-policy-document "$TRUST_POLICY" \
  --tags "Key=Project,Value=${PROJECT}" >/dev/null
info "Created role $ROLE_NAME"

# AWS-managed policy for SSM Session Manager. Attaching this one managed
# policy is safer than hand-rolling an equivalent that AWS keeps updating.
aws iam attach-role-policy --role-name "$ROLE_NAME" \
  --policy-arn "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
info "Attached AmazonSSMManagedInstanceCore (browser shell, no SSH keys needed)"

# Our own tightly scoped policy for reading the secret.
POLICY_NAME="${PROJECT}-read-db-secret-${SUFFIX}"
save POLICY_NAME "$POLICY_NAME"

SECRET_POLICY=$(cat <<JSON
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ReadOnlyTheKeycloakSecrets",
      "Effect": "Allow",
      "Action": [
        "secretsmanager:GetSecretValue",
        "secretsmanager:DescribeSecret"
      ],
      "Resource": "arn:aws:secretsmanager:${AWS_DEFAULT_REGION}:${ACCOUNT_ID}:secret:${PROJECT}/db-*"
    }
  ]
}
JSON
)

POLICY_ARN=$(aws iam create-policy \
  --policy-name "$POLICY_NAME" \
  --description "Read only the Keycloak database secret" \
  --policy-document "$SECRET_POLICY" \
  --query 'Policy.Arn' --output text)
save POLICY_ARN "$POLICY_ARN"

aws iam attach-role-policy --role-name "$ROLE_NAME" --policy-arn "$POLICY_ARN"
info "Attached $POLICY_NAME - scoped to ${PROJECT}/db-* only"

# ---------------------------------------------------------------------------
# 9. Instance profile
# ---------------------------------------------------------------------------
step "9/9  Creating the instance profile"
# EC2 cannot attach a role directly. It needs an "instance profile", which is
# just a thin wrapper around one role. Terraform hides this; the CLI does not.

PROFILE_NAME="${PROJECT}-keycloak-profile-${SUFFIX}"
save PROFILE_NAME "$PROFILE_NAME"

aws iam create-instance-profile --instance-profile-name "$PROFILE_NAME" >/dev/null
aws iam add-role-to-instance-profile \
  --instance-profile-name "$PROFILE_NAME" --role-name "$ROLE_NAME"

# IAM is eventually consistent: the profile can take a few seconds to become
# usable. Sleeping here avoids a confusing "invalid instance profile" error
# when the EC2 instance launches in script 03.
info "Waiting 15s for IAM to propagate..."
sleep 15

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
step "NETWORK LAYER COMPLETE"
cat <<SUMMARY

  VPC ................. $VPC_ID
  Public subnet ....... $PUBLIC_SUBNET_ID
  Private subnets ..... $PRIVATE_SUBNET_A , $PRIVATE_SUBNET_B
  Keycloak firewall ... $KEYCLOAK_SG_ID   (open to $MY_IP_CIDR only)
  Database firewall ... $DB_SG_ID   (open to the Keycloak SG only)
  IAM role ............ $ROLE_NAME
  Instance profile .... $PROFILE_NAME

  Estimated cost of THIS script: \$0.00/month
  (VPCs, subnets, security groups, route tables, IGWs and IAM are all free.)

  Next:  ./02-create-database.sh

SUMMARY
